4.9.74-ti-rt-r90 release
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/patches/readme/0001-enable-Jenkins-http-rcn-ee.online-8080.patch b/patches/readme/0001-enable-Jenkins-http-rcn-ee.online-8080.patch
--- a/patches/readme/0001-enable-Jenkins-http-rcn-ee.online-8080.patch
+++ b/patches/readme/0001-enable-Jenkins-http-rcn-ee.online-8080.patch
@@ -1,25 +1,113 @@
-From 8a9cbe539f109d815efe3bfea2e3c898a1d32940 Mon Sep 17 00:00:00 2001
+From 840f6b5f58891538c201e1d2aa353a0fd335042e Mon Sep 17 00:00:00 2001
 From: Robert Nelson <robertcnelson@gmail.com>
-Date: Tue, 3 Oct 2017 22:14:31 -0500
+Date: Fri, 5 Jan 2018 15:14:44 -0600
 Subject: [PATCH] enable: Jenkins: http://rcn-ee.online:8080
 
 Signed-off-by: Robert Nelson <robertcnelson@gmail.com>
 ---
- README.md | 5 +++++
- 1 file changed, 5 insertions(+)
+ Jenkinsfile      | 11 ++++++++++
+ README.md        |  5 +++++
+ jenkins_build.sh | 61 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ 3 files changed, 77 insertions(+)
+ create mode 100644 Jenkinsfile
  create mode 100644 README.md
+ create mode 100755 jenkins_build.sh
 
+diff --git a/Jenkinsfile b/Jenkinsfile
+new file mode 100644
+index 000000000000..fc0b0fafa435
+--- /dev/null
++++ b/Jenkinsfile
+@@ -0,0 +1,11 @@
++pipeline {
++    agent any
++
++    stages {
++        stage('Build') {
++            steps {
++                sh '/bin/bash ./jenkins_build.sh' 
++            }
++        }
++    }
++}
 diff --git a/README.md b/README.md
 new file mode 100644
-index 000000000000..30fb20637bff
+index 000000000000..f5c168ec6f07
 --- /dev/null
 +++ b/README.md
 @@ -0,0 +1,5 @@
-+| kernel | normal | rt | xenomai |
-+|:---------:|:--------:|:-------:|:-------:|
-+|4.4 | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.4)](http://rcn-ee.online:8080/job/bb.org_linux_4.4/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.4-rt)](http://rcn-ee.online:8080/job/bb.org_linux_4.4-rt/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.4-xenomai)](http://rcn-ee.online:8080/job/bb.org_linux_4.4-xenomai/) |
-+|4.9 | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.9)](http://rcn-ee.online:8080/job/bb.org_linux_4.9/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.9-rt)](http://rcn-ee.online:8080/job/bb.org_linux_4.9-rt/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.9-xenomai)](http://rcn-ee.online:8080/job/bb.org_linux_4.9-xenomai/) |
-+|4.14 | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.14)](http://rcn-ee.online:8080/job/bb.org_linux_4.14/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.14-rt)](http://rcn-ee.online:8080/job/bb.org_linux_4.14-rt/) | |
++| kernel | normal | rt |
++|:---------:|:--------:|:-------:|
++|4.4 | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.4)](http://rcn-ee.online:8080/job/bb.org_linux_4.4/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.4-rt)](http://rcn-ee.online:8080/job/bb.org_linux_4.4-rt/) |
++|4.9 | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.9)](http://rcn-ee.online:8080/job/bb.org_linux_4.9/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.9-rt)](http://rcn-ee.online:8080/job/bb.org_linux_4.9-rt/) |
++|4.14 | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.14)](http://rcn-ee.online:8080/job/bb.org_linux_4.14/) | [![Build Status](http://rcn-ee.online:8080/buildStatus/icon?job=bb.org_linux_4.14-rt)](http://rcn-ee.online:8080/job/bb.org_linux_4.14-rt/) |
+diff --git a/jenkins_build.sh b/jenkins_build.sh
+new file mode 100755
+index 000000000000..c3e7d066d2e7
+--- /dev/null
++++ b/jenkins_build.sh
+@@ -0,0 +1,61 @@
++#!/bin/bash
++
++#gcc:
++
++site="https://releases.linaro.org"
++
++gcc_version="6.4"
++gcc_minor=".1"
++release="17.11"
++target="arm-linux-gnueabihf"
++
++version="components/toolchain/binaries/${gcc_version}-20${release}/${target}"
++filename="gcc-linaro-${gcc_version}${gcc_minor}-20${release}-x86_64_${target}.tar.xz"
++directory="gcc-linaro-${gcc_version}${gcc_minor}-20${release}-x86_64_${target}"
++
++datestamp="${gcc_version}-20${release}-${target}"
++
++binary="bin/${target}-"
++#
++
++if [ ! -d ${directory}/ ] ; then
++	rm -rf ./gcc-* || true
++	#wget -c ${site}/${version}/${filename}
++	wget -c http://rcn-ee.online/builds/jenkins-dl/${filename}
++	tar xf ${filename}
++fi
++
++export CC=`pwd`/${directory}/bin/arm-linux-gnueabihf-
++
++make ARCH=arm clean
++make ARCH=arm bb.org_defconfig
++
++echo "[make ARCH=arm -j2 CROSS_COMPILE=\"${binary}\" zImage]"
++make ARCH=arm -j2 CROSS_COMPILE="ccache ${CC}" zImage
++if [ ! -f arch/arm/boot/zImage ] ; then
++	echo "failed: [arch/arm/boot/zImage]"
++	exit 1
++fi
++
++echo "[make ARCH=arm -j2 CROSS_COMPILE=\"${binary}\" modules]"
++make ARCH=arm -j2 CROSS_COMPILE="ccache ${CC}" modules
++if [ ! -f drivers/spi/spidev.ko ] ; then
++	echo "failed: [drivers/spi/spidev.ko]"
++	exit 1
++fi
++
++echo "[make ARCH=arm -j2 CROSS_COMPILE=\"${binary}\" dtbs]"
++make ARCH=arm -j2 CROSS_COMPILE="ccache ${CC}" dtbs
++if [ ! -f arch/arm/boot/dts/am335x-boneblack.dtb ] ; then
++	echo "failed: [arch/arm/boot/dts/am335x-boneblack.dtb]"
++	exit 1
++else
++	if [ -f arch/arm/boot/dts/am335x-pocketbeagle.dts ] ; then
++		if [ ! -f arch/arm/boot/dts/am335x-pocketbeagle.dtb ] ; then
++			echo "failed: [arch/arm/boot/dts/am335x-pocketbeagle.dtb]"
++			exit 1
++		fi
++	fi
++fi
++
++make ARCH=arm clean
 -- 
-2.14.2
+2.15.1
 
