merge ti: https://github.com/RobertCNelson/ti-linux-kernel/compare/0c460d4caf692125372361d2e7bbe133e002e37a...cf63b764bdea23417d60e1e8158c6f01e8846014
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/patches/packaging/0001-packaging-sync-builddeb-changes.patch b/patches/packaging/0001-packaging-sync-builddeb-changes.patch
--- a/patches/packaging/0001-packaging-sync-builddeb-changes.patch
+++ b/patches/packaging/0001-packaging-sync-builddeb-changes.patch
@@ -1,15 +1,101 @@
-From c328e909073836ff1505e2e0ca05ed3ddb3ff7be Mon Sep 17 00:00:00 2001
+From 46602c57118ac6d930b9f86a25964faf33db0fb1 Mon Sep 17 00:00:00 2001
 From: Robert Nelson <robertcnelson@gmail.com>
-Date: Thu, 14 Dec 2017 10:13:05 -0600
+Date: Mon, 4 Jun 2018 11:10:07 -0500
 Subject: [PATCH] packaging: sync builddeb changes
 
 Signed-off-by: Robert Nelson <robertcnelson@gmail.com>
 ---
- scripts/package/builddeb | 25 +++++++++++++++----------
- 1 file changed, 15 insertions(+), 10 deletions(-)
+ scripts/package/Makefile | 42 +++++++++++++++++++++++++++-------------
+ scripts/package/builddeb | 29 +++++++++++++++------------
+ 2 files changed, 46 insertions(+), 25 deletions(-)
 
+diff --git a/scripts/package/Makefile b/scripts/package/Makefile
+index 7badec3498b8..9fbcf5ed0ca7 100644
+--- a/scripts/package/Makefile
++++ b/scripts/package/Makefile
+@@ -32,10 +32,14 @@ MKSPEC     := $(srctree)/scripts/package/mkspec
+ 
+ quiet_cmd_src_tar = TAR     $(2).tar.gz
+       cmd_src_tar = \
++set -e; \
+ if test "$(objtree)" != "$(srctree)"; then \
+-	echo "Building source tarball is not possible outside the"; \
+-	echo "kernel source tree. Don't set KBUILD_OUTPUT, or use the"; \
+-	echo "binrpm-pkg or bindeb-pkg target instead."; \
++	echo >&2; \
++	echo >&2 "  ERROR:"; \
++	echo >&2 "  Building source tarball is not possible outside the"; \
++	echo >&2 "  kernel source tree. Don't set KBUILD_OUTPUT, or use the"; \
++	echo >&2 "  binrpm-pkg or bindeb-pkg target instead."; \
++	echo >&2; \
+ 	false; \
+ fi ; \
+ $(srctree)/scripts/setlocalversion --save-scmversion; \
+@@ -45,26 +49,22 @@ rm -f $(objtree)/.scmversion
+ 
+ # rpm-pkg
+ # ---------------------------------------------------------------------------
+-rpm-pkg rpm: FORCE
++rpm-pkg: FORCE
+ 	$(MAKE) clean
+ 	$(CONFIG_SHELL) $(MKSPEC) >$(objtree)/kernel.spec
+ 	$(call cmd,src_tar,$(KERNELPATH),kernel.spec)
+-	$(CONFIG_SHELL) $(srctree)/scripts/mkversion > $(objtree)/.tmp_version
+-	mv -f $(objtree)/.tmp_version $(objtree)/.version
+-	rpmbuild $(RPMOPTS) --target $(UTS_MACHINE) -ta $(KERNELPATH).tar.gz
+-	rm $(KERNELPATH).tar.gz kernel.spec
++	+rpmbuild $(RPMOPTS) --target $(UTS_MACHINE) -ta $(KERNELPATH).tar.gz \
++	--define='_smp_mflags %{nil}'
+ 
+ # binrpm-pkg
+ # ---------------------------------------------------------------------------
+ binrpm-pkg: FORCE
+ 	$(MAKE) KBUILD_SRC=
+ 	$(CONFIG_SHELL) $(MKSPEC) prebuilt > $(objtree)/binkernel.spec
+-	$(CONFIG_SHELL) $(srctree)/scripts/mkversion > $(objtree)/.tmp_version
+-	mv -f $(objtree)/.tmp_version $(objtree)/.version
+-
+-	rpmbuild $(RPMOPTS) --define "_builddir $(objtree)" --target \
++	+rpmbuild $(RPMOPTS) --define "_builddir $(objtree)" --target \
+ 		$(UTS_MACHINE) -bb $(objtree)/binkernel.spec
+-	rm binkernel.spec
++
++clean-files += $(objtree)/*.spec
+ 
+ # Deb target
+ # ---------------------------------------------------------------------------
+@@ -98,6 +98,21 @@ bindeb-pkg: FORCE
+ 
+ clean-dirs += $(objtree)/debian/
+ 
++# snap-pkg
++# ---------------------------------------------------------------------------
++snap-pkg: FORCE
++	rm -rf $(objtree)/snap
++	mkdir $(objtree)/snap
++	$(MAKE) clean
++	$(call cmd,src_tar,$(KERNELPATH))
++	sed "s@KERNELRELEASE@$(KERNELRELEASE)@; \
++		s@SRCTREE@$(shell realpath $(KERNELPATH).tar.gz)@" \
++		$(srctree)/scripts/package/snapcraft.template > \
++		$(objtree)/snap/snapcraft.yaml
++	cd $(objtree)/snap && \
++	snapcraft --target-arch=$(UTS_MACHINE)
++
++clean-dirs += $(objtree)/snap/
+ 
+ # tarball targets
+ # ---------------------------------------------------------------------------
+@@ -142,6 +157,7 @@ help: FORCE
+ 	@echo '  binrpm-pkg          - Build only the binary kernel RPM package'
+ 	@echo '  deb-pkg             - Build both source and binary deb kernel packages'
+ 	@echo '  bindeb-pkg          - Build only the binary kernel deb package'
++	@echo '  snap-pkg            - Build only the binary kernel snap package (will connect to external hosts)'
+ 	@echo '  tar-pkg             - Build the kernel as an uncompressed tarball'
+ 	@echo '  targz-pkg           - Build the kernel as a gzip compressed tarball'
+ 	@echo '  tarbz2-pkg          - Build the kernel as a bzip2 compressed tarball'
 diff --git a/scripts/package/builddeb b/scripts/package/builddeb
-index 3c575cd07888..c2920e79c763 100755
+index 0a2a7372538c..f947e76a7d84 100755
 --- a/scripts/package/builddeb
 +++ b/scripts/package/builddeb
 @@ -69,7 +69,7 @@ set_debarch() {
@@ -98,6 +184,18 @@ index 3c575cd07888..c2920e79c763 100755
  Architecture: any
  Description: Linux kernel debugging symbols for $version
   This package will come in handy if you need to debug the kernel. It provides
+@@ -438,9 +443,9 @@ EOF
+ 	dpkg-source -cdebian/control -ldebian/changelog --format="3.0 (custom)" --target-format="3.0 (quilt)" \
+ 		-b / ../${sourcename}_${version}.orig.tar.gz  ../${sourcename}_${packageversion}.debian.tar.gz
+ 	mv ${sourcename}_${packageversion}*dsc ..
+-	dpkg-genchanges > ../${sourcename}_${packageversion}_${debarch}.changes
++	dpkg-genchanges -Vkernel:debarch="${debarch}" > ../${sourcename}_${packageversion}_${debarch}.changes
+ else
+-	dpkg-genchanges -b > ../${sourcename}_${packageversion}_${debarch}.changes
++	dpkg-genchanges -b -Vkernel:debarch="${debarch}" > ../${sourcename}_${packageversion}_${debarch}.changes
+ fi
+ 
+ exit 0
 -- 
-2.15.1
+2.17.1
 
